defaults:
  - data: cloudes
  - network: MMFN
  - _self_

tag: "default_run"

trainer:
  max_epochs: 50
  enable_progress_bar: False

optimizer_cfg:
  _target_: torch.optim.Adam
  _partial_: true
  weight_decay: 1e-5